//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanLuongBTP
    {
        public string MaSP { get; set; }
        public string MS_DV { get; set; }
        public System.DateTime Ngay { get; set; }
        public decimal SoLuong { get; set; }
        public bool IsSapData { get; set; }
        public System.Guid Id { get; set; }
    }
}
